# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.define "vm1" do |vm1|
    vm1.vm.box = "centos/7"
    vm1.vm.hostname = "vm1"
  end
  config.vm.provider "virtualbox1" do |vm1|
    vm1.name = "vm1"
    vm1.memory = 2048
  end

  config.vm.define "vm2" do |vm2|
    vm2.vm.box = "ubuntu/focal64"
    vm2.vm.hostname = "vm2"
  end
  config.vm.provider "virtualbox2" do |vm2|
    vm2.name = "vm2"
    vm2.memory = 2048
  end
end
